### PR TITLE
Added fix seed command and regex replacement capability

### PR DESCRIPTION
**Pull request by djsalvat**
Added command to fix the seed to a particular value.
Kept the existing seed command the same, so macros should
be backwards compatible.

Changed volID assignment to instead take a replacement pattern
to determine the volID to set based on the match. This casts
the replacement string to an int, so it should not break
any existing functionality -- if you use a constant int
for the second argument, it will just be cast to int appropriately
anyway.

One potential issue to address down the line is that the regex replacement does not check whether the user attempts to set it to 0 or -1. This could potentially be added back in to the stepping action when checked in some way.

### CODE REVIEW

**Comment by jasondet** [comment]
Hey Dan! Nice changes. Sorry I only just now go around to reviewing them. Some comments before I merge:

- Can you provide a non-trivial example in the .mac for how to use the [replacement] pattern?
- Your addition removes a check on user-supplied IDs in old-code line 124: they should not be 0 or -1, so as not to break the code around lines 200-220 (see especially 211 in the new code). Can you add a comment in your guidance that the replacement pattern should not generate 0 or -1, and also a test (maybe after new-code line 207) that replacement not evaluate to these numbers, emitting a warning as necessary?
- Is your new set seed command different from the existing G4 standard command /random/setSeed? If not, let's remove it and just use the G4 standard.

**Comment by jasondet** [comment]
Hey Dan -- I just submitted a bunch of updates we needed for LEGEND. You will want to pull (from upstream) and make sure what you want to do still works.

**Comment by jasondet** [comment]
Hi Dan, you still interested in merging this PR? I think some people would be interested in the cmake feature and regexp features especially. j

**Comment by djsalvat** [comment]
Looking at this again now. Addressing the 3 bullets in order:

- Yes, I will produce one.
- Let me check this. I think I should be able to make these changes.
- Does the /random/setSeed command work with g4simple's random implementation? If so, then yes by all means, I'll get rid of that.

I propose the following:
I think we could/should regex and CMake changes two separate commits just for clealiness. If so, can you download the CMake file and try building on a mac? Should be able to follow the commands in the comments at the top of the CMakeLists.txt file. I have tested on linux successfully, but I think we should do a test on mac, and I don't have a mac machine handy.

If that passes, I will modify the PR to just commit the CMakeLists.txt file, and in the mean time will go back and clean up the regex changes for a separate PR.

Do you agree with this?

**Comment by djsalvat** [comment]
Actually now that I look, I did make them two separate non-conflicting commits. I guess if the mac test passes, you can just pull that?

**Comment by jasondet** [comment]
Yes, I'll check the cmake file.

**Comment by jasondet** [comment]
Nice, it works. But only if I comment out the lines that try to put run.mac and vis.mac into a "scripts" directory under the install location. Those macros are now in the examples directory, and were really only meant as examples anyway. We want users to write their own .mac's. Should we just delete the whole /scripts section of the cmake install? Other than that it looks ready to go.

**Comment by djsalvat** [comment]
Yeah, forgot about that. I guess we can just omit that, and make the install basically just have the binary. We could have the "make install" also copy the Examples/ folder (which isn't an unusual way to go), but maybe for now I'll just nix it -- it can always be added back in later.

**Pull request closed without merging**
